name: server
description: A web server built using the shelf package.
version: 0.0.1
#homepage: https://www.example.com
#author: mauricioschneider <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^0.13.7
  shelf: ^0.6.0
  grinder: ^0.8.0+3

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

compiler:
  debug: dartdevc
